parameters:
    looptribe.formspatial.form.type.pointclass: Looptribe\FormSpatialBundle\Form\Type\PointType

services:
    looptribe.formspatial.form.type.point:
        class: "%looptribe.formspatial.form.type.pointclass%"
        arguments: ["%looptribe.formspatial.google_maps_api_key%"]
        tags:
            - { name: form.type, alias: point }
